# KEEP THIS FILE OUT OF VCS
TELEGRAM_TOKEN = "PASTE_YOUR_TELEGRAM_TOKEN_HERE"
OPENAI_API_KEY = "PASTE_YOUR_OPENAI_KEY_HERE"
OPENAI_BASE_URL = "https://api.proxyapi.ru/openai/v1"
OPENAI_MODEL = "gpt-4.1"
